// Additional differential cases against the complete pinned t0.js behavior.
// These are trusted terminating programs. Host-only fetch/debugger effects and
// malformed-source bugs are tested/documented separately from language values.
export const fullCases = [
  { name: 'empty pop is undefined', source: 'print + print' },
  { name: 'coercion in arithmetic', source: 'true true + print false 3 - print " 7" 2 * print " " 2 * print \'abc 2 - print' },
  { name: 'array coercion in addition', source: '[ 1 2 ] [ 3 4 ] + print [ ] 1 + print 2 \'x + print' },
  { name: 'strict equality and identity', source: 'false 0 = print [ ] [ ] = print [ ] :a a a = print 0 0 / dup = print -0 0 = print' },
  { name: 'lexical string and numeric comparisons', source: '" 20" " 3" < print " 20" 3 < print " 20" 20 = print " a" " b" <= print' },
  { name: 'null and undefined comparisons', source: '" x" 99 charAt dup print 0 <= print [ ] 0 @ dup print 0 < print' },
  { name: 'negative zero and remainder signs', source: '-0 print 1 -0 / print 1 -4 2 mod / print -5 2 mod print 5 -2 mod print' },
  { name: 'parseFloat decimal prefix and special values', source: '"   -12.5e2tail" parseFloat print \'1e parseFloat print \'0x10 parseFloat print \'Infinity parseFloat print \'-Infinity parseFloat print " " parseFloat print' },
  { name: 'whole-string number conversions', source: '\'0x10 1 * print \'0b11 1 * print \'0o10 1 * print \'12tail 1 * print "  12  " 1 * print' },
  { name: 'array and null number conversions', source: '[ ] 1 * print [ 3 ] 2 * print [ 1 2 ] 1 * print " x" 9 charAt 1 * print [ ] 0 @ 1 * print' },
  { name: 'pow exceptional values', source: '-2 0.5 ^ print 0 -1 ^ print 0 0 / 0 ^ print 1 -0 3 ^ / print' },
  { name: 'pow fractional values', source: '9 0.5 ^ print 2 -3 ^ print 27 0.3333333333333333 ^ print' },
  { name: 'IEEE754 overflow underflow and NaN', source: '1e308 1e308 * print 5e-324 2 / print 0 0 / print 1 0 / 1 0 / - print' },
  { name: 'number formatting thresholds', source: '1e-7 print 1e-6 print 1e20 print 1e21 print 1000000000000000100 print 5e-324 print' },
  { name: 'binary64 precision', source: '0.1 0.2 + print 9007199254740992 1 + print 1.2345678901234567 print' },
  { name: 'UTF16 string length and indexing', source: '" A😀B" len print " A😀B" 1 charAt len print " A😀B" 3 charAt print " éλ中" len print' },
  { name: 'UTF16 surrogate construction', source: '55357 charCode 56832 charCode + print 65537 charCode len print -1 charCode len print' },
  { name: 'string indexed access differs from charAt', source: '" abc" -1 charAt print " abc" 8 charAt print " abc" 8 @ print " abc" 1.9 charAt print " abc" 1.9 @ print' },
  { name: 'charAt NaN and negative indices', source: '" abc" 0 0 / charAt print " abc" -0.5 charAt print " abc" -1 charAt len print' },
  { name: 'indexOf converts search values', source: '" abc123null" 123 indexOf print " abc123null" " x" 9 charAt indexOf print " abc" " " indexOf print' },
  { name: 'strings types and concatenation', source: '" é😀" \'x + print " x" string? print [ ] string? print [ ] array? print " x" array? print' },
  { name: 'quoted whitespace and triple quotes', source: '"   two spaces" print """ text with " inside""" print' },
  { name: 'array growth and holes', source: '[ 1 ] :a 9 a 3 :@ a len print a 1 @ print a 3 @ print a print' },
  { name: 'array string properties', source: '[ 1 2 ] :a 42 a \'answer :@ a \'answer @ print a \'length @ print a len print a print' },
  { name: 'array noninteger keys', source: '[ 10 20 ] :a 9 a 1.5 :@ 8 a \'01 :@ a 1.5 @ print a \'01 @ print a 1 @ print a len print' },
  { name: 'closure own numeric and string properties', source: '{ | } :f 9 f 0 :@ f 0 @ print 8 f \'answer :@ f \'answer @ print' },
  { name: 'length and indexing on primitive values', source: '1 len print true len print { x | x } len print 1 0 @ print true \'length @ print " abc" \'length @ print' },
  { name: 'array length shrink and regrow', source: '[ 1 2 3 ] :a 1 a \'length :@ a print a len print 3 a \'length :@ a 2 @ print a print' },
  { name: 'cyclic array conversion', source: '[ ] :a a a 0 :@ a print a len print a a 0 @ = print' },
  { name: 'nested arrays string conversion', source: '[ 1 [ 2 3 ] [ ] true false ] print' },
  { name: 'array constructors fractional counts', source: '2.5 \'x []WithValue dup len print print 2.5 { i | i } []WithFn print -1 9 []WithValue len print' },
  { name: 'array constructor count coercion', source: '" 3" 7 []WithValue print true { i | i } []WithFn print' },
  { name: 'array constructor reevaluates shrinking count', source: '[ 3 ] :shrinkingBound shrinkingBound { i | 1 shrinkingBound 0 :@ i } []WithFn print' },
  { name: 'array constructor reevaluates growing count', source: '[ 1 ] :growingBound growingBound { i | 3 growingBound 0 :@ i } []WithFn print' },
  { name: 'array constructor returns before massive allocation', source: '{ :constructorDone | 1000000000 { i | 7 constructorDone<- } []WithFn } () print' },
  { name: 'pick depth and coercion', source: '10 20 30 0 pick print 1 pick print " 1" pick print true pick print -1 pick print 1.5 pick print' },
  { name: 'logical operators preserve operands', source: '0 42 & print 3 42 & print 0 42 | print 3 42 | print " " ! print [ ] ! print' },
  { name: 'lazy operator result semantics', source: '3 { | 42 } || print 0 { | 42 } || print 0 { | 42 } && print 3 { | 42 } && print' },
  { name: 'late forward reference resolves definition', source: '{ | later } :readLater 42 :later readLater () print' },
  { name: 'compiled automatic call binds old definition', source: '{ | 1 } ::value { | value } :old { | 2 } ::value old () print value print' },
  { name: 'semicolon definitions', source: 'answer: 42 ; answer print 43 \'answer const answer print' },
  { name: 'method dispatch and receiver', source: '{ m | m switch \'value { this | 42 } { this | 0 } end } :object object .value print' },
  { name: 'switch literal results and default', source: '2 switch 1 \'one 2 \'two \'other end print 9 switch 1 \'one \'other end print' },
  { name: 'switch keys run at compile time', source: '1 :key { | 1 switch key { | 10 } { | 20 } end () } :f 2 :key f () print' },
  { name: 'compile-time side effects happen once', source: '{ | i[ \'compiling print 1 2 + emit ] } :f f () print f () print' },
  { name: 'emitted array identity persists', source: '[ 1 ] :constantArray { | i[ constantArray emit ] } :f f () :a 9 a 0 :@ f () 0 @ print' },
  { name: 'dictionary lookup observes updated global', source: '1 :answer { | \'answer ?? } :readAnswer 2 :answer readAnswer () print' },
  { name: 'dictionary lookup in closure local scope', source: '{ n let 7 :value | { | \'n ?? \'value ?? + } } :factory 5 factory () () print' },
  { name: 'labelled return across while', source: '{ :exit | 1 { | true } { | 2 exit<- 3 } while 4 } () print print' },
  { name: 'local return preserves earlier stack', source: '99 { | 1 <- 2 } () print print' },
  { name: 'runtime input and instruction position', source: 'input_ print ip_ print' },
  { name: 'nested eval restores source input', source: '{ | input_ } :s " s ()" eval print input_ print' },
  { name: 'eval with no usable source length is a no-op', source: '1 eval false eval { | 99 } eval [ ] eval 42 print' },
  { name: 'compiled ip reads runtime source position', source: '{ | ip_ } :readIp readIp () print' },
  { name: 'closure source string', source: '{ x | x 2 * } print' },
  { name: 'debugger is operationally inert without debugger', source: '1 debugger 2 + print' },
];
