// The adapted, upstream-derived JS-like frontend. These expectations describe
// this documented dialect, not ECMAScript conformance. Every case starts fresh;
// sources within one case share their dictionary and persistent data stack.
export const jsCases = [
  { name: 'precedence and grouping', sources: ['5 * 2 ** (2 + 3) + 100'], expected: [260] },
  { name: 'left associative subtraction', sources: ['10 - 3 - 2'], expected: [5] },
  { name: 'left associative division', sources: ['8 / 4 / 2'], expected: [1] },
  { name: 'right associative exponentiation', sources: ['2 ** 3 ** 2'], expected: [512] },
  { name: 'remainder is not T0 percent', sources: ['17 % 5'], expected: [2] },
  { name: 'fractional division', sources: ['1 / 2'], expected: [0.5] },
  { name: 'decimal literal', sources: ['1.5 + 2.25'], expected: [3.75] },
  { name: 'leading decimal point', sources: ['.5 * 4'], expected: [2] },
  { name: 'trailing decimal point', sources: ['1. + 2.'], expected: [3] },
  { name: 'signed exponent', sources: ['1e3 + 2E-3'], expected: [1000.002] },
  { name: 'unary minus', sources: ['-2 * 3 + -0.5'], expected: [-6.5] },
  { name: 'negative exponent', sources: ['2 ** -2'], expected: [0.25] },
  { name: 'binary64 rounding', sources: ['0.1 + 0.2'], expected: [0.30000000000000004] },
  { name: 'infinity', sources: ['1 / 0'], expected: [{ type: 'number', value: 'Infinity' }] },
  { name: 'NaN', sources: ['0 / 0'], expected: [{ type: 'number', value: 'NaN' }] },
  { name: 'comparison and equality', sources: ['1 < 2; 2 == 2; 2 != 3; 3 > 2 > 1'], expected: [true, true, true, false] },
  { name: 'boolean negation', sources: ['!false'], expected: [true] },
  { name: 'short circuit avoids missing variable', sources: ['false && missing; true || missing'], expected: [false, true] },
  { name: 'empty and nested arrays', sources: ['[]; [1,[2,3],true][1][0]'], expected: [[], 2] },
  { name: 'trailing array comma', sources: ['[1,2,]'], expected: [[1, 2]] },
  { name: 'variables persist across lines', sources: ['answer = 40', 'answer + 2'], expected: [40, 42] },
  { name: 'assignment inside expression', sources: ['(answer=20)+22; answer'], expected: [42, 20] },
  { name: 'sequential assignment', sources: ['answer=1;answer=answer+1;answer'], expected: [1, 2, 2] },
  { name: 'prefix and postfix mutation', sources: ['i=1;i++;++i;i--;--i;i'], expected: [1, 1, 3, 3, 1, 1] },
  { name: 'if without else', sources: ['if(true) 42', 'if(false) 99'], expected: [42] },
  { name: 'if else blocks', sources: ['if(2>1){1+2}else{3*4}', 'if(false){10}else{20}'], expected: [3, 20] },
  { name: 'ternary expression', sources: ['true ? 1 : 2; false ? 1 : 2'], expected: [1, 2] },
  { name: 'false while', sources: ['while(false){1;2}'], expected: [] },
  { name: 'while updates persistent variable', sources: ['i=0', 'while(i<3)i=i+1', 'i'], expected: [0, 1, 2, 3, 3] },
  { name: 'while block and increment', sources: ['i=0;total=0;while(i<4){total=total+i;i++;};total'], expected: [0, 0, 0, 0, 1, 1, 3, 2, 6, 3, 6] },
  { name: 'statement stack behavior', sources: ['{1;2;3;}'], expected: [1, 2, 3] },
  { name: 'comments and blank lines', sources: ['// leading comment\n1 + 2 // last comment', '// only a comment', ''], expected: [3] },
  { name: 'named function declaration and call', sources: ['function square(x){return x*x;} square(9)'], expected: [81] },
  { name: 'anonymous function immediate call', sources: ['(function(a,b){return a+b;})(20,22)'], expected: [42] },
  { name: 'function fallthrough is undefined', sources: ['function quiet(){1;2;3;} quiet()'], expected: [{ type: 'undefined' }] },
  { name: 'undefined literal', sources: ['undefined'], expected: [{ type: 'undefined' }] },
  { name: 'function local mutable counter', sources: ['function make(start){let n=start;return function(){n++;return n;};} let counter=make(3);', 'counter()', 'counter()'], expected: [4, 5] },
  { name: 'function local let has function scope', sources: ['function f(){if(true){let x=42;}return x;} f()'], expected: [42] },
  { name: 'function local let has no temporal dead zone', sources: ['function f(){return x;let x=42;} f()'], expected: [{ type: 'undefined' }] },
  { name: 'top level let does not leave initializer on stack', sources: ['let answer=40;answer+2'], expected: [42] },
  { name: 'single parameter arrow', sources: ['(x=>x*2)(21)'], expected: [42] },
  { name: 'multiple parameter arrow', sources: ['((a,b)=>a+b)(20,22)'], expected: [42] },
  { name: 'block arrow with return', sources: ['(()=>{let x=41;return x+1;})()'], expected: [42] },
  { name: 'nested arrow lexical capture', sources: ['(x=>y=>x+y)(40)(2)'], expected: [42] },
  { name: 'indexed arrow function', sources: ['[x=>x+1,x=>x*2][1](21)'], expected: [42] },
  { name: 'keyword prefixes remain valid identifiers', sources: ['let returnValue=42;returnValue'], expected: [42] },

  { name: 'function parameter calls callback', sources: ['(function(f){return f(21);})(x=>x*2)'], expected: [42] },
  { name: 'function primitive name hygiene', sources: ['function f(dup,swap,mod){let x=1;x++;return (y=>y+40)(x)+(8%3)-2;} f(100,100,100)'], expected: [42] },
  { name: 'function interpreter metadata name hygiene', sources: ['function f(input,ip){return input+ip;} f(20,22)'], expected: [42] },

];

export const invalidJSCases = [
  '1 trailing',
  '1 2',
  'a b',
  '1 +',
  '(1+2',
  '[1,2',
  'if(true)',
  'while(true)',
  '1.2.3',
  '1e',
  '1e+',
  '3**',
  'const answer=42',
  '"hello"',
  '1===1',
  '1 < = 2',
  'return 1;',
  'if(true){return 1;}',
  'function f(x){return x;',
  'function f(x{return x;}',
  'function f(){const x=1;return x;}',
  'function f(){return 1 2;}',
  'function f(){return 1;} trailing junk',
  'f(1,',
  '()=>',
  '(x,y)=>{return x+y;',
  'if=42',
  'let true=1',

];
